### PR TITLE
marker creators utility

### PR DESCRIPTION
**Pull request by sarthou**
This pull request does not affect the classic behavior of ar_track_alvar but adds two utilities that allow you to simply create **remote markers** (on XYZ) and **cubes** with six markers.

Based on sampleMarkerCreator, it generates the PNG and XML files with the corresponding transformations.

In addition, it allows users to create color markers for more diversity.

> A readme file explaining the use of the utility is present in the folder ar_track_alvar

### CODE REVIEW

**Comment by 130s** [comment]
Could you rebase to the origin, which has been slightly updated? CI failed and [I see](https://travis-ci.org/ros-perception/ar_track_alvar/jobs/346813229#L1405) memory allocation error, which may or may not be already addressed by the latest change.

**Comment by sarthou** [comment]
It sounds better but I do not understand why some CI have failed

**Review by 130s — COMMENTED** [review]
- CI failed because it detected ABI breakage with some of the changes added in this PR. See e.g. [this CI result](https://travis-ci.org/ros-perception/ar_track_alvar/jobs/382053393#L1233).
  - General question is, do we want to keep ABI compatibility or not. I would say yes; as I've seen certain amount of questions on answers.ros.org and on this repo, I can assume there are a good number of users who build their application using the library of the pkg.
  - So the choice is to either a) change this PR so that it won't break ABI, b) aim the latest ROS distro Melodic. Create a new branch for that and re-target this PR to that branch. What do you think @sarthou?
- I'd like to ask a favor; Can you convert [README](https://github.com/ros-perception/ar_track_alvar/blob/b32295f552813203b9fb992e02c2b37fc30a646e/README) file to markdown format, then add the document you're adding into that file as a section? Because this repo is basically missing the readme in the top level at the moment, it'd be good to have one. Also, your addition is not super large, it makes more sense to be added within the main doc.
- Whitespace removal is helpful in general. Please just keep in mind adding them as a separate commit (if separating it from now is too difficult, I guess that's fine just for this time..).

**Comment by sarthou** [comment]
* Normally, I just added some small correction and I removed a lot of warning in the ABI so these changes are interesting in my opinion, so I think it would be better to re-target this PR on the branch Melodic

* No problem for the README file, I'll do it
* Really sorry for spaces, my text editor does it automatically ... I'll be more careful next time

**Comment by 130s** [comment]
Okay, then I just created `melodic-devel` branch and made it a default for this repo. I have to ask you to re-open a PR targeting there, as I don't think there's a feature to change the target branch on this PR. Thanks @sarthou!

**Comment by 130s** [comment]
Note `melodic-devel` is based off from `kinetic-devel`, so you should be able to use the same branch of yours and just change the target branch when you open a new PR.

**Pull request closed without merging**
